// Global using directives

global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Tasks;
global using AutoMapper;
global using MMS.DataManager.NotificationManagement.Hubs;
global using MMS.DataManager.NotificationManagement.Localization;
global using MMS.DataManager.NotificationManagement.Notifications;
global using MMS.DataManager.NotificationManagement.Notifications.Aggregates;
global using MMS.DataManager.NotificationManagement.Notifications.LocalEvents;
global using MMS.DataManager.NotificationManagement.Notifications.Dtos;
global using MMS.DataManager.NotificationManagement.Notifications.Enums;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.SignalR;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Volo.Abp;
global using Volo.Abp.Application;
global using Volo.Abp.Application.Dtos;
global using Volo.Abp.Application.Services;
global using Volo.Abp.AspNetCore.SignalR;
global using Volo.Abp.Auditing;
global using Volo.Abp.AutoMapper;
global using Volo.Abp.DependencyInjection;
global using Volo.Abp.EventBus;
global using Volo.Abp.Modularity;
global using Volo.Abp.Users;